### ISSUE TITLE
Character limit 

### ISSUE THREAD

**Issue by ghost** [Naki21/google-speech-to-text#2]
Is there a way to limit the lines by characters?

**Comment by Naki21** [comment]
Could you please elaborate? Lines in the text file or the .srt file? What is the problem you are running into?

**Comment by alexwrd** [comment]
Hi, sorry for not being clear. The .srt file, i tried to limit the number
of characters in every line but i couldn't figure out how to do so.

**Comment by Naki21** [comment]
So the way I have it set up it to be able to limit the lines by words. If you look in format_response.py, there is a formula I use called chunks(). I wrote this formula because most lines more than 14 words long led to subtitles being more than two lines long, causing them to block images in the video. You could reduce the word count if this is the same problem you are running into. 

If you are looking to limit by characters specifically you would need to write a formula similar to chunks() which uses character count instead of word count and apply it accordingly.

**Comment by alexwrd** [comment]
Yeah, I know but I'm not sure how to do it. It seems that if you use 'word'
in 'word_info' you can't sync the words to the video. And with 'words' in
'alternative' you can measure the quantity not the length directly, unless
you do something where if the length of 'word' in 'word_info' + length of
the line don't exceeds x, you append the ''word_info' to the line so that
you can still have the timestamps. And then you can do th e loop .
